Advanced camera calibration (#98)
* add to_array convenience method

* add methods to create a route for undistorted images

* create route for undistorted images on startup

* add fisheye parameter and alternative methods
add methods for un- and redistortion of images and points

* fix fisheye projection and add fisheye calibration

* add fisheye calibration tests

* fix fisheye calibration flags

* explicitly add width and height default values

* uncomment code that rejects points behind camera

* add docstrings

* add center_point property to easily get the translation as a Point3d

* add omnidirectional camera model

* add warning and exception logging

* replace fisheye parameter with new camera_model parameter

* fix pinhole points not being converted to homogeneous coordinates

* handle SE3 arrays as rotation input

* always use perspective undistortion for omni cameras

* convert parameters to the data structures opencv expects

* remove commented-out code

* convert numpy array to list

* minor cleanup

* add class docstrings and use double quotes

* add tests for omnidirectional cameras

* code review

* use correct model type

* add focal_length option to set_perfect_calibration

* Fix pytest error "AttributeError: module 'cv2.omnidir' has no attribute 'projectPoints'" (#127)

* debug opencv error

* poetry lock

* try without headless

* cleanup

* use multiple views in omnidirectional calibration

* use opencv-contrib headless again

* add psmisc install to make sure fuser is available

* Merge branch 'main' into advanced_camera_calibration

* downgrade to previous versions in petry lock

* update contrib-python and add libgl1 import

* update opencv-python to match contrib modules

* make sure opencv is installed before its contrib packages

* add script to install opencv-contrib after opencv and match its version

* improve method order

* code review

---------

Co-authored-by: Falko Schindler <falko@zauberzeug.com>